### ISSUE TITLE
default run.env has an incorrect value for DR_TRAIN_ROUND_ROBIN_ADVANCE_DIST

### ISSUE THREAD

**Issue by MaikelGit** [aws-deepracer-community/deepracer-on-the-spot#75]
DR_TRAIN_ROUND_ROBIN_ADVANCE_DIST=0.05
should be
DR_TRAIN_ROUND_ROBIN_ADVANCE_DIST=0.1
when given hyperparameters file has 20 episodes and system.env has a 2 workers

DR_TRAIN_ROUND_ROBIN_ADVANCE_DIST is the result of the number of workers divided number of episodes, 2/20 = 0.1

**Comment by MarkRoss-Eviden** [comment]
I agree there's an issue, but we should keep DR_TRAIN_ROUND_ROBIN_ADVANCE_DIST=0.05 as it's the same as the console default, and change the episodes to 40.

**Comment by MaikelGit** [comment]
well, 40 episodes won't be default console value either for the console.
the other option is to set number of workers default value to 1. that way
we can keep 20 episodes and 0.05, but they is going against the spirit of
taking more advantage of the ec2 instances resources.  in my opinion, 0.05
it is not the default value from the console. the default value from the
console is workers/episodes formula result, not the value itself. why don't
we change the value with a formula as another option? thanks for feedback

**Comment by MarkRoss-Eviden** [comment]
The console defaults are 1 worker, 20 episodes, 0.05 advanced distance (i.e. car moves 5% along the track for each episode in the iteration).  

My request to change what you suggested will make the DOTS defaults 2 workers, 40 episodes and 0.05 advanced distance.

My rationale for this is: -
 - benefit from multi-workers, as you also suggest above
 - maintain each iteration moving forward 5% of the track, so that the training benefits from learning smaller chunks of the track, 10% on large tracks can be quite a lot of waypoints.  This maintains consistency with console defaults
 - 40 episodes are divided equally between the workers, so each worker will get 20 episodes each, so each worker will maintain the same as what happens in the console (albeit there will be 2 of them)

If you can update the PR and the readm.md in custom-files I'm happy to merge it as Tyler made me a maintainer of the repo to help out with capacity

**Comment by MarkRoss-Eviden** [comment]
Fixed by https://github.com/aws-deepracer-community/deepracer-on-the-spot/pull/82
